config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :bugs
  root 'bugs#index'
  get '/contact' => 'bugs#new'

end

app/models/bug.rb
class Bug < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true
  validates :description, presence: true
  enum status: [:open, :closed, :monitor]
  enum issue_type: [:issue, :enhancment, :feature]
  enum priority: [:low, :medium, :high]
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :fname, :lname, presence: true
 
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 105},
        uniqueness: { case_sensitive: false },
        format: { with: VALID_EMAIL_REGEX }
  

 validates :thumbnail, allow_blank: true, format: {with:
        %r{\.(gif|jpg|png)\Z}i,
        message: 'must be a URL for GIF, JPG or PNG image.'}
      
  has_many :bugs

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  respond_to :html, :js 
  before_action :set_statuses
  before_action :set_issue_types
  before_action :set_priorities
  before_action :set_bug, only: [:show, :edit, :update, :destroy]
  before_action :all_bugs, only:[:index, :create, :destroy, :update]
  
  
  def all_bugs
    @bugs = Bug.all
  end


  # GET /bugs
  # GET /bugs.json
  def index
    @bugs = Bug.all
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
  end

  # GET /bugs/new
  def new
    @bug = Bug.new
  end

  # GET /bugs/1/edit
  def edit
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(bug_params)
    user = User.find(bug_params[:user_id])
    @bug.build_user(:id => user.id)
    @bug.save!
    @current_bug = @bug
  end

  # def create
  #   @bug = Bug.new(bug_params)

  #   respond_to do |format|
  #     if @bug.save
  #       format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
  #       format.json { render :show, status: :created, location: @bug }
  #       user = User.find(bug_params[:user_id])
  #       @bug.build_user(:id => user.id)
  #     else
  #       format.html { render :new }
  #       format.json { render json: @bug.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /bugs/1
  # PATCH/PUT /bugs/1.json
  def update
    @bug.update!(bug_params)
  end

  # def update
  #   respond_to do |format|
  #     if @bug.update(bug_params)
  #       format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @bug }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @bug.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug.destroy!
  end
  # def destroy
  #   @bug.destroy
  #   respond_to do |format|
  #     format.html { redirect_to bugs_url, notice: 'Bug was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bug
      @bug = Bug.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bug_params
      params.require(:bug).permit(:title, :description, :issue_type, :priority, :status, :user_id)
    end
    
  def set_statuses
    @statuses = Bug.statuses
  end
  
  def set_issue_types
    @issue_types = Bug.issue_types
  end
  
  def set_priorities
    @priorities = Bug. priorities
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:fname, :lname, :email, :thumbnail)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bugs/_bug.html.erb
<tr 
<% if  bug.priority == 'high'  && bug.status != 'closed'  %>
class = "important bug"
<% else %>
  class = "bug"
 <% end %>
 <% if bug == @current_bug %>
   id ="current_bug"
   <% end %> >
  <td><%= ((bug.user.try(:fname) || " ") + " "+ (bug.user.try(:lname) ||" ") || "NA") %></td>
  <td><%= bug.title %></td>
  <td><%= bug.description %></td>
  <td><%= bug.issue_type %></td>
  <td><%= bug.priority %></td>
  <td><%= bug.status %></td>
  <td><%= link_to 'Show', bug %></td>
  <td><%= link_to 'Edit', edit_bug_path(bug), remote: true %></td>
  <td><%= link_to 'Destroy', bug, method: :delete, data: { confirm: 'Are you sure?' }, remote: true %></td>
</tr>

app/views/bugs/_form.html.erb
<%= form_for(@bug,   remote: true) do |f| %>
  <% if @bug.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

      <ul>
      <% @bug.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.select :user_id,
    options_for_select(User.all.collect {|u| ["#{u.lname},
    #{u.fname}", u.id]},
    selected: (@bug.user ? @bug.user.id : User.first.id)),
    {} %>
  </div>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :issue_type %><br>
        <%= f.label :issue_type %><br>
        <%= f.select :issue_type, options_for_select(@issue_types.collect {|s| [s[0].humanize, s[0]]},
          selected: @bug.issue_type), {} %>
  </div>
  <div class="field">
    <%= f.label :priority %><br>
        <%= f.select :priority, options_for_select(@priorities.collect {|s| [s[0].humanize, s[0]]},
      selected: @bug.priority), {} %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.select :status, options_for_select(@statuses.collect {|s| [s[0].humanize, s[0]]},
      selected: @bug.status), {} %>
  </div>
  <div class="actions" id = "submitbutton">
    <%= f.submit %>
  </div>
<% end %>

app/views/bugs/create.js.erb
$('#bugs').html(" <%= j (render @bugs) %> ");
$('#bug-form').slideUp(350);
$('#current_bug').css({'background-color' : '#88ff88'}).animate({'background-color' 
: '#ffffff'}, 3000);

app/views/bugs/destroy.js.erb
$('#bugs').html("<%= j (render @bugs) %>");

app/views/bugs/edit.html.erb
<h1>Editing Bug</h1>

<%= render 'form' %>

<%= link_to 'Show', @bug %> |
<%= link_to 'Back', bugs_path %>

app/views/bugs/edit.js.erb
$('#bug-form').html("<%= j (render 'form') %>");
$('#bug-form').slideDown(350);
    setTimeout(function(){ 
        if((obj =   document.getElementById("submitbutton")) && obj != null) {
            window.scrollTo(0, obj.offsetTop);
        } 
    }, 400);

app/views/bugs/index.html.erb
<p id="notice"><%= notice %></p>
<div class="btn"><%= link_to 'New Bug', new_bug_path, remote: true %></div>
<h1>Listing Bugs</h1>
<table >
  <thead>
    <tr>
      <th>User</th>
      <th>Title</th>
      <th>Description</th>
      <th>Issue type</th>
      <th>Priority</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id = "bugs">

    <%= render @bugs %>

  </tbody>
  
</table>

<div id="bug-form" style="display:none;"></div>
<br>

app/views/bugs/new.html.erb
<h1>New Bug</h1>

<%= render 'form' %>

<%= link_to 'Back', bugs_path %>

app/views/bugs/new.js.erb
$('#bug-form').html("<%= j (render 'form') %>");
$('#bug-form').slideDown(350);
setTimeout(function(){ 
    if((obj = document.getElementById("submitbutton")) && obj != null){
        window.scrollTo(0, obj.offsetTop);
    } 
}, 400);

app/views/bugs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bug.title %>
</p>

<p>
  <strong>User:</strong>
  <%= ((@bug.user.try(:fname) || " ") + " " + (@bug.user.try(:lname) || " ") || "NA")%>
</p>

<p>
  <strong>Description:</strong>
  <%= @bug.description %>
</p>

<p>
  <strong>Issue type:</strong>
  <%= @bug.issue_type %>
</p>

<p>
  <strong>Priority:</strong>
  <%= @bug.priority %>
</p>

<p>
  <strong>Status:</strong>
  <%= @bug.status %>
</p>

<%= link_to 'Edit', edit_bug_path(@bug) %> |
<%= link_to 'Back', bugs_path %>

app/views/bugs/update.js.erb
$('#bugs').html("<%= j (render @bugs) %>");
$('#bug-form').slideUp(350);

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bugaroo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="header">
     <a href = "/"><img src="http://media.merchantcircle.com/21310320/hpclogo_full.jpeg" alt="Help Desk" style="width:100px;height:75px;"></a>
    <div id="title">
     <%= @page_title || "The Help Desk Site!" %><!-- <label id="code.depot.e.title"/> -->
  
   </div>
   

 </div>
 <div id="sidebar">

  <div id = "menu">
    <ul class="menu">
      <li><a  href = "/">Home</a></li>
      <li><a  href = "/users">Users</a></li>
      <li><a  href = "/bugs">Bugs</a></li>
      <li><a  href = "/contact">Contact Us</a></li>
    </ul>
  </div>
 </div>
  <div id="main">
    <%= yield %>
  </div>
</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :fname %><br>
    <%= f.text_field :fname %>
  </div>
  <div class="field">
    <%= f.label :lname %><br>
    <%= f.text_field :lname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :thumbnail %><br>
    <%= f.text_field :thumbnail %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<div class="btn"><%= link_to 'New User', new_user_path %></div>
<h1>Listing Users</h1>

<table id="userTable">
  <thead>
    <tr>
      <th>Fname</th>
      <th>Lname</th>
      <th>Email</th>
      <th>Thumbnail</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.fname %></td>
        <td><%= user.lname %></td>
        <td><%= user.email %></td>
        <td><%= image_tag(user.thumbnail, alt: user.thumbnail, size: "50x50") %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @user.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @user.lname %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Thumbnail:</strong>
  <%= image_tag(@user.thumbnail, alt: @user.thumbnail, size: "100x100") %>
</p>

  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>